# Generated by Django 3.0.8 on 2020-10-02 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('enable_alert', models.BooleanField(default=False)),
                ('alert_date', models.DateTimeField(default=datetime.datetime.now)),
                ('alert_text', wagtail.fields.RichTextField(blank=True)),
                ('alert_colour', models.CharField(choices=[('R', 'Red'), ('G', 'Green')], default='G', max_length=1)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_col_heading', models.CharField(blank=True, max_length=200)),
                ('footer_col', wagtail.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('telephone', wagtail.blocks.StructBlock([('telephone', wagtail.blocks.CharBlock(classname='telephone'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('email', wagtail.blocks.StructBlock([('email', wagtail.blocks.EmailBlock(classname='email'))]))], blank=True)),
            ],
            options={
                'verbose_name': 'First Footer Column',
            },
        ),
        migrations.CreateModel(
            name='FooterColumnTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_col_two_heading', models.CharField(blank=True, max_length=200)),
                ('footer_col_two', wagtail.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('telephone', wagtail.blocks.StructBlock([('telephone', wagtail.blocks.CharBlock(classname='telephone'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('email', wagtail.blocks.StructBlock([('email', wagtail.blocks.EmailBlock(classname='email'))]))], blank=True)),
            ],
            options={
                'verbose_name': 'Second Footer Column',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
