# Generated by Django 3.0.8 on 2020-11-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterColumnTwo',
        ),
    ]
