# Generated by Django 3.0.8 on 2020-11-26 03:31

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0003_auto_20201124_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercolumn',
            name='footer_col_heading',
        ),
        migrations.AlterField(
            model_name='footercolumn',
            name='footer_col',
            field=wagtail.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('telephone', wagtail.blocks.StructBlock([('telephone', wagtail.blocks.CharBlock(classname='telephone'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('email', wagtail.blocks.StructBlock([('email', wagtail.blocks.EmailBlock(classname='email'))])), ('show_business_hours', wagtail.blocks.BooleanBlock(help_text='If checked, the library hours will display on the page', icon='user', required=False)), ('show_next_closure', wagtail.blocks.BooleanBlock(help_text='If checked, the next library closure will display', icon='user', required=False)), ('show_all_closures', wagtail.blocks.BooleanBlock(help_text='If checked, all upcoming library closures will be shown', icon='user', required=False)), ('book_list_block', wagtail.snippets.blocks.SnippetChooserBlock(icon='list-ol', target_model='book_list.bookList'))], blank=True),
        ),
    ]
