# Generated by Django 5.2.5 on 2025-09-23 21:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0003_closeddate_closed_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeddate',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='closeddate',
            name='featured_on_home_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='closeddate',
            name='closed_date_name',
            field=models.TextField(default='Holiday'),
        ),
        migrations.AlterField(
            model_name='closeddate',
            name='closed_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
