# Generated by Django 3.2.8 on 2023-03-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_allpurposepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectorpage',
            name='redirect_to',
            field=models.URLField(help_text='The URL to redirect to', max_length=2000),
        ),
    ]
