# Generated by Django 3.2.8 on 2023-07-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('page', '0010_alter_allpurposepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpurposepage',
            name='form_page',
            field=models.ForeignKey(blank=True, help_text='Select a Form that will be embedded on this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_page_embed', to='wagtailcore.page'),
        ),
    ]
