# Generated by Django 3.2.8 on 2023-03-21 00:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('side_menu', wagtail.fields.StreamField([('side_menu', wagtail.blocks.StructBlock([('side_menu_title', wagtail.blocks.CharBlock()), ('side_menu_body', wagtail.blocks.StreamBlock([('side_menu_item', wagtail.blocks.StructBlock([('pdf_document', wagtail.documents.blocks.DocumentChooserBlock(required=False))], icon='openquote', template='person/blocks/side_menu_item.html'))]))], icon='collapse-down', template='person/blocks/side_menu.html'))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='personEntry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.CharField(max_length=165)),
                ('biography', wagtail.fields.RichTextField()),
                ('image', models.ForeignKey(help_text='upload an image for the bio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
