# Generated by Django 3.2.8 on 2023-03-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personentry',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
