# Generated by Django 5.2.9 on 2026-04-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_personentry_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='personentry',
            name='show_first',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
