# Generated by Django 3.2.8 on 2023-02-17 18:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('background_image_w_searchbar', wagtail.images.blocks.ImageChooserBlock(icon='collapse-down', template='home/blocks/background_image_w_searchbar.html')), ('aspen_carousel', wagtail.blocks.StructBlock([('aspen_carousel_title', wagtail.blocks.CharBlock(help_text='The title of the carousel to be displayed on the homepage', required=True)), ('aspen_iframetag', wagtail.blocks.CharBlock(help_text='requires an Aspen Discovery iframe tag. Go to https://search.pentictonlibrary.ca/Admin/CollectionSpotlights for more info', icon='collapse-down', required=True, template='home/blocks/aspen_carousel.html'))], template='home/blocks/aspen_carousel.html')), ('upcoming_events_features', wagtail.blocks.BooleanBlock(default=1, help_text='If checked BOTH the three program features plus an upcoming events list row will display', icon='tasks', required=False)), ('single_feature', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='The internal page to link to', required=False)), ('single_feature_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('single_feature_description', wagtail.blocks.CharBlock(help_text='write a short description of the feature', required=True)), ('override_title', wagtail.blocks.CharBlock(help_text="OPTIONAL, only use this if you'd like to override the name of the page you are linking to", required=False)), ('enabled', wagtail.blocks.BooleanBlock(default=True, required=False))], icon='image', template='home/blocks/single_feature.html')), ('feature_row', wagtail.blocks.StructBlock([('feature_row_title', wagtail.blocks.CharBlock(help_text='Pick a title for your list of features', required=True)), ('feature_body', wagtail.blocks.StreamBlock([('feature', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='The internal page to link to', required=False)), ('feature_document', wagtail.documents.blocks.DocumentChooserBlock(help_text='OPTIONAL: use this to link to a PDF document instead of a page', required=False)), ('feature_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('feature_text', wagtail.blocks.CharBlock(help_text="OPTIONAL, only use this if you'd like to override the name of the page you are linking to", required=False))], icon='openquote', template='home/blocks/feature.html'))]))], icon='image', template='home/blocks/feature_row.html'))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
