# Generated by Django 5.0.6 on 2024-06-20 21:51

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('background_image_w_searchbar', wagtail.images.blocks.ImageChooserBlock(icon='collapse-down', template='home/blocks/background_image_w_searchbar.html')), ('aspen_carousel', wagtail.blocks.StructBlock([('aspen_carousel_title', wagtail.blocks.CharBlock(help_text='The title of the carousel to be displayed on the homepage', required=True)), ('aspen_iframetag', wagtail.blocks.CharBlock(help_text='requires an Aspen Discovery iframe tag. Go to https://search.pentictonlibrary.ca/Admin/CollectionSpotlights for more info', icon='collapse-down', required=True, template='home/blocks/aspen_carousel.html'))], template='home/blocks/aspen_carousel.html')), ('upcoming_events_features', wagtail.blocks.BooleanBlock(default=1, help_text='If checked BOTH the three program features plus an upcoming events list row will display', icon='tasks', required=False)), ('single_feature', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='The internal page to link to', required=False)), ('single_feature_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('single_feature_video_embed', wagtail.blocks.RawHTMLBlock(help_text='Embed a video using an iframe tag provided by youTube, or another source instead of displaying the image.', required=False)), ('single_feature_description', wagtail.blocks.CharBlock(help_text='write a short description of the feature', required=True)), ('override_title', wagtail.blocks.CharBlock(help_text="OPTIONAL, only use this if you'd like to override the name of the page you are linking to", required=False)), ('enabled', wagtail.blocks.BooleanBlock(default=True, required=False))], icon='image', template='home/blocks/single_feature.html')), ('feature_row', wagtail.blocks.StructBlock([('feature_row_title', wagtail.blocks.CharBlock(help_text='Pick a title for your list of features', required=True)), ('feature_body', wagtail.blocks.StreamBlock([('feature', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(help_text='The internal page to link to', required=False)), ('feature_document', wagtail.documents.blocks.DocumentChooserBlock(help_text='OPTIONAL: use this to link to a PDF document instead of a page', required=False)), ('feature_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('feature_text', wagtail.blocks.CharBlock(help_text="OPTIONAL, only use this if you'd like to override the name of the page you are linking to", required=False))], icon='openquote', template='home/blocks/feature.html'))]))], icon='image', template='home/blocks/feature_row.html'))], blank=True),
        ),
    ]
