# Generated by Django 5.2.5 on 2025-10-03 23:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('background_image_w_searchbar', 0), ('aspen_carousel', 3), ('upcoming_events_features', 4), ('single_feature', 12), ('feature_row', 18)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'collapse-down', 'template': 'home/blocks/background_image_w_searchbar.html'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title of the carousel to be displayed on the homepage', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'requires an Aspen Discovery iframe tag. Go to https://search.pentictonlibrary.ca/Admin/CollectionSpotlights for more info', 'icon': 'collapse-down', 'required': True, 'template': 'home/blocks/aspen_carousel.html'}), 3: ('wagtail.blocks.StructBlock', [[('aspen_carousel_title', 1), ('aspen_iframetag', 2)]], {'template': 'home/blocks/aspen_carousel.html'}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': 1, 'help_text': 'If checked BOTH the three program features plus an upcoming events list row will display', 'icon': 'tasks', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'The internal page to link to', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Embed a video using an iframe tag provided by youTube, or another source instead of displaying the image.', 'required': False}), 8: ('home.models.AudioVideoBlock', (), {'icon': 'media', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'write a short description of the feature', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': "OPTIONAL, only use this if you'd like to override the name of the page you are linking to", 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('page', 5), ('single_feature_image', 6), ('single_feature_video_embed', 7), ('single_feature_video_upload', 8), ('single_feature_description', 9), ('override_title', 10), ('enabled', 11)]], {'icon': 'image', 'template': 'home/blocks/single_feature.html'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Pick a title for your list of features', 'required': True}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'OPTIONAL: use this to link to a PDF document instead of a page', 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 16: ('wagtail.blocks.StructBlock', [[('page', 5), ('feature_document', 14), ('feature_image', 15), ('feature_text', 10)]], {'icon': 'openquote', 'template': 'home/blocks/feature.html'}), 17: ('wagtail.blocks.StreamBlock', [[('feature', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('feature_row_title', 13), ('feature_body', 17)]], {'icon': 'image', 'template': 'home/blocks/feature_row.html'})}),
        ),
    ]
