# Generated by Django 3.2.8 on 2023-02-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercolumn',
            name='order',
            field=models.IntegerField(help_text='uses bootstrap grid Order class. https://getbootstrap.com/docs/5.0/layout/columns/#reordering', null=True),
        ),
    ]
