# Generated by Django 5.2.1 on 2025-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0003_alter_footercolumn_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_end_date',
            field=models.DateTimeField(blank=True, help_text='If entered, the time the alert should be removed from public view', null=True),
        ),
    ]
