# Generated by Django 5.2.1 on 2025-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0004_alert_alert_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='enable_alert',
            field=models.BooleanField(default=True),
        ),
    ]
