# Generated by Django 5.2.1 on 2025-05-14 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0005_alter_alert_enable_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The start of the alert'),
        ),
    ]
