# Generated by Django 5.2.1 on 2025-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0006_alter_alert_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='enable_alert',
            field=models.BooleanField(default=False),
        ),
    ]
