# Generated by Django 5.2.1 on 2025-05-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0007_alter_alert_enable_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='enable_alert',
            field=models.BooleanField(default=True),
        ),
    ]
