# Generated by Django 3.2.8 on 2023-05-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('library_programs', '0002_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_page',
            field=models.ForeignKey(blank=True, help_text='Select a Form that will be embedded on this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedded_form_page', to='wagtailcore.page'),
        ),
    ]
