# Generated by Django 3.2.8 on 2023-06-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0003_event_form_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Enter a location where the event will happen', max_length=500, null=True),
        ),
    ]
