# Generated by Django 4.2.1 on 2023-08-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0004_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hide_from_home_page',
            new_name='featured_on_home_page',
        ),
    ]
