# Generated by Django 3.2.8 on 2023-08-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0005_rename_hide_from_home_page_event_featured_on_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tutorial_link',
            field=models.CharField(blank=True, help_text='for showing Niche Academy Links or similar', max_length=255),
        ),
    ]
