# Generated by Django 5.1.3 on 2025-03-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0008_registrationformpage_event_enable_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformpage',
            name='honeypot',
            field=models.BooleanField(default=False, verbose_name='Honeypot Enabled'),
        ),
    ]
