# Generated by Django 5.2.5 on 2025-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0009_registrationformpage_honeypot'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Check to have the library program display as all day, instead of a time range'),
        ),
    ]
