# Generated by Django 5.2.5 on 2025-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0010_event_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Check if this event is all day'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
