# Generated by Django 5.2.5 on 2025-10-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0011_alter_event_all_day_alter_event_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='close_reg_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
