# Generated by Django 5.2.5 on 2025-10-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0012_event_close_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='close_reg_date',
            field=models.DateTimeField(blank=True, help_text='Date the registration form will be removed from the page. Otherwise closes after the program ends.', null=True, verbose_name='Close Registration Form'),
        ),
    ]
