# Generated by Django 5.2.8 on 2025-11-13 19:40

import library_programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0013_alter_event_close_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_reg_date',
            field=models.DateTimeField(blank=True, help_text='Date the registration form will be viewable on the page.', null=True, verbose_name='Open Registration Form'),
        ),
        migrations.AlterField(
            model_name='registrationformfield',
            name='label',
            field=models.CharField(help_text='The label of the form field, cannot be one of the following: Email.', max_length=255, validators=[library_programs.models.validate_label], verbose_name='label'),
        ),
    ]
