# Generated by Django 5.2.9 on 2026-03-18 01:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0014_event_open_reg_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, max_length=2500, null=True),
        ),
    ]
