# Generated by Django 6.0.4 on 2026-04-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0015_alter_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationformpage',
            name='honeypot',
        ),
    ]
