# Generated by Django 6.0.4 on 2026-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_programs', '0016_remove_registrationformpage_honeypot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformfield',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='help text'),
        ),
    ]
