# Generated by Django 4.2.7 on 2024-04-30 03:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('library_news', '0002_newsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='content',
            field=wagtail.fields.StreamField([('quote', wagtail.blocks.BlockQuoteBlock(help_text="Enter the text you'd like to appear in quotation marks", required=True)), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True),
        ),
    ]
