# Generated by Django 4.2.7 on 2024-05-01 02:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('library_news', '0004_remove_newsitem_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=wagtail.fields.StreamField([('quote', wagtail.blocks.BlockQuoteBlock(help_text="Enter the text you'd like to appear in quotation marks", required=True)), ('quote_block', wagtail.blocks.StructBlock([('quote', wagtail.blocks.BlockQuoteBlock(help_text="Enter the text you'd like to appear in quotation marks", required=True)), ('attribution', wagtail.blocks.CharBlock(help_text='attribute the quote to someone', required=False))], icon='openquote')), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True),
        ),
    ]
