# Generated by Django 3.2.8 on 2023-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='honeypot',
            field=models.BooleanField(default=False, verbose_name='Honeypot Enabled'),
        ),
    ]
