# Generated by Django 6.0.4 on 2026-04-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0002_formpage_honeypot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='honeypot',
        ),
    ]
