# Generated by Django 6.0.4 on 2026-07-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0003_remove_formpage_honeypot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='help text'),
        ),
    ]
