# Generated by Django 3.2.8 on 2023-04-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineresourcepage',
            name='tutorial_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
