# Generated by Django 3.2.8 on 2023-05-05 23:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_resource', '0003_onlineresourceindexpage_niche_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineresourcepage',
            name='featured_description',
            field=wagtail.fields.RichTextField(blank=True, max_length=400),
        ),
    ]
